/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicIndexRouteImport } from './routes/public/index'
import { Route as DiaryIndexRouteImport } from './routes/diary/index'
import { Route as PublicIdRouteImport } from './routes/public/$id'
import { Route as DiaryNewRouteImport } from './routes/diary/new'
import { Route as DiaryIdRouteImport } from './routes/diary/$id'
import { Route as DiaryIdEditRouteImport } from './routes/diary/$id_.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/public/',
  path: '/public/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryIndexRoute = DiaryIndexRouteImport.update({
  id: '/diary/',
  path: '/diary/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIdRoute = PublicIdRouteImport.update({
  id: '/public/$id',
  path: '/public/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryNewRoute = DiaryNewRouteImport.update({
  id: '/diary/new',
  path: '/diary/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryIdRoute = DiaryIdRouteImport.update({
  id: '/diary/$id',
  path: '/diary/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryIdEditRoute = DiaryIdEditRouteImport.update({
  id: '/diary/$id_/edit',
  path: '/diary/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/diary/$id': typeof DiaryIdRoute
  '/diary/new': typeof DiaryNewRoute
  '/public/$id': typeof PublicIdRoute
  '/diary/': typeof DiaryIndexRoute
  '/public/': typeof PublicIndexRoute
  '/diary/$id/edit': typeof DiaryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/diary/$id': typeof DiaryIdRoute
  '/diary/new': typeof DiaryNewRoute
  '/public/$id': typeof PublicIdRoute
  '/diary': typeof DiaryIndexRoute
  '/public': typeof PublicIndexRoute
  '/diary/$id/edit': typeof DiaryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/diary/$id': typeof DiaryIdRoute
  '/diary/new': typeof DiaryNewRoute
  '/public/$id': typeof PublicIdRoute
  '/diary/': typeof DiaryIndexRoute
  '/public/': typeof PublicIndexRoute
  '/diary/$id_/edit': typeof DiaryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/diary/$id'
    | '/diary/new'
    | '/public/$id'
    | '/diary/'
    | '/public/'
    | '/diary/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/diary/$id'
    | '/diary/new'
    | '/public/$id'
    | '/diary'
    | '/public'
    | '/diary/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/diary/$id'
    | '/diary/new'
    | '/public/$id'
    | '/diary/'
    | '/public/'
    | '/diary/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  DiaryIdRoute: typeof DiaryIdRoute
  DiaryNewRoute: typeof DiaryNewRoute
  PublicIdRoute: typeof PublicIdRoute
  DiaryIndexRoute: typeof DiaryIndexRoute
  PublicIndexRoute: typeof PublicIndexRoute
  DiaryIdEditRoute: typeof DiaryIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/': {
      id: '/public/'
      path: '/public'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary/': {
      id: '/diary/'
      path: '/diary'
      fullPath: '/diary/'
      preLoaderRoute: typeof DiaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$id': {
      id: '/public/$id'
      path: '/public/$id'
      fullPath: '/public/$id'
      preLoaderRoute: typeof PublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary/new': {
      id: '/diary/new'
      path: '/diary/new'
      fullPath: '/diary/new'
      preLoaderRoute: typeof DiaryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary/$id': {
      id: '/diary/$id'
      path: '/diary/$id'
      fullPath: '/diary/$id'
      preLoaderRoute: typeof DiaryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary/$id_/edit': {
      id: '/diary/$id_/edit'
      path: '/diary/$id/edit'
      fullPath: '/diary/$id/edit'
      preLoaderRoute: typeof DiaryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  DiaryIdRoute: DiaryIdRoute,
  DiaryNewRoute: DiaryNewRoute,
  PublicIdRoute: PublicIdRoute,
  DiaryIndexRoute: DiaryIndexRoute,
  PublicIndexRoute: PublicIndexRoute,
  DiaryIdEditRoute: DiaryIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
